name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-west-2
      - name : installation
        run : |
          confd_ver='0.16.0'
          confd_url="https://github.com/kelseyhightower/confd/releases/download/v$confd_ver/confd-$confd_ver-linux-amd64"
          wget $confd_url
          chmod +x confd-$confd_ver-linux-amd64
          sudo mv confd-$confd_ver-linux-amd64 /bin/confd 
          sudo mkdir -p /etc/confd/conf.d
          sudo mkdir -p /etc/confd/templates 
          sudo cp -rf ${{ github.workspace }}/etc/confd/*  /etc/confd/
          sudo rm -rf /tmp/confd
          sudo touch /var/log/confd.log
          sudo su - root
          chmod -R 777 /var/log/confd.log
          sudo confd -onetime -backend ssm > /var/log/confd.log 2>&1
