name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Fetch SSM Parameter values
        id: fetch-ssm-values
        run: |
          echo "::set-output name=host::$(aws ssm get-parameter --name /myapp/database/host --query 'Parameter.Value' --output text)"
          echo "::set-output name=port::$(aws ssm get-parameter --name /myapp/database/port --query 'Parameter.Value' --output text)"
          echo "::set-output name=username::$(aws ssm get-parameter --name /myapp/database/username --query 'Parameter.Value' --output text)"
          echo "::set-output name=password::$(aws ssm get-parameter --name /myapp/database/password --query 'Parameter.Value' --output text)"

      - name: Run tests with fetched values
        run: |
          php test.php ${{ steps.fetch-ssm-values.outputs.host }} ${{ steps.fetch-ssm-values.outputs.port }} ${{ steps.fetch-ssm-values.outputs.username }} ${{ steps.fetch-ssm-values.outputs.password }}
