name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-west-2
      - name : installation
        run : |
            wget https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64
            mkdir -p /opt/confd/bin
            mv confd-0.16.0-linux-amd64 /opt/confd/bin/confd
            chmod +x /opt/confd/bin/confd
            export PATH="$PATH:/opt/confd/bin"
            confd -version
      - name : fetch value
        run : |
           cd /opt/confd/bin/
           confd -onetime -backend ssm
           
        
   
